# Generated by Django 5.0.6 on 2026-05-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Farmer's phone number receiving this # Core user fields(OTP)",
                        max_length=15,
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        help_text="6-digit one-time password", max_length=6
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Time when this OTP expires and cannot be used."
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="True if this code has already been verified",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when this OTP code was generated",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="is_agronomist",
            field=models.BooleanField(
                default=False,
                help_text="Expert user(agronomist) who can access web dashboard and review disease predictions?",
                verbose_name="Is Agronomist",
            ),
        ),
    ]
