# Generated by Django 5.0.6 on 2026-05-30 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="Farmer;s question", verbose_name="Question"
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Generated answer from RAG system",
                        verbose_name="Answer",
                    ),
                ),
                (
                    "sources",
                    models.JSONField(
                        default=list,
                        help_text="List of PDF sources used for answer",
                        verbose_name="Sources",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the question was asked",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Farmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat History",
                "verbose_name_plural": "Chat Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
