# Generated by Django 5.0.6 on 2026-05-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranslationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_text",
                    models.TextField(
                        help_text="The original text to translate (e.g., 'How to treat late blight?')"
                    ),
                ),
                (
                    "source_language",
                    models.CharField(
                        help_text="Language code of original text (e.g., 'en' for English, 'yo' for Yoruba)",
                        max_length=10,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        help_text="Language code to translate to (e.g., 'yo', 'ha', 'ig', 'pcm', 'ar', 'fr')",
                        max_length=10,
                    ),
                ),
                (
                    "translated_text",
                    models.TextField(help_text="The chched translated text result"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this translation was first cached",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this translation was last accessed (for cache cleanup)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Cache",
                "verbose_name_plural": "Translation Caches",
                "indexes": [
                    models.Index(
                        fields=["source_language", "target_language"],
                        name="translation_source__a3e42d_idx",
                    )
                ],
                "unique_together": {
                    ("original_text", "source_language", "target_language")
                },
            },
        ),
    ]
